<?php
	
	$GermanLicensePlateLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	$GermanLicensePlates = array(
	    "NRW" => array(
		    "AC" => "Aachen",
			"BI" => "Bielefeld",
			"BM" => "Erftkreis (Bergheim)",
			"BN" => "Bonn",
			"BOR" => "Borken",
			"COE" => "Coesfeld",
			"DN" => "Düren",
			"EU" => "Euskirchen",
			"GL" => "Rheinisch-Bergischer-Kreis (Bergisch-Gladbach)",
			"GM" => "Oberbergischer Kreis (Gummersbach)",
			"GT" => "Gütersloh",
			"HAM" => "Hamm",
			"HF" => "Herford",
			"HS" => "Heinsberg",
			"HSK" => "Hochsauerlandkreis",
			"HX" => "Höxter",
			"K" => "Köln",
			"KLE" => "Kleve",
			"LEV" => "Leverkusen",
			"LIP" => "Lippe",
			"MI" => "Minden-Lübbecke",
			"MK" => "Märkischer Kreis",
			"MS" => "Münster",
			"OE" => "Olpe",
			"PB" => "Paderborn",
			"RE" => "Recklinghausen",
			"SI" => "Siegen",
			"SO" => "Soest",
			"ST" => "Steinfurt",
			"SU" => "Rhein-Sieg-Kreis (Siegburg)",
			"UN" => "Unna",
			"VIE" => "Viersen",
			"WAF" => "Warendorf",
			"WES" => "Wesel",
			"WIT" => "Witten",
			"BO" => "Bochum",
			"BOT" => "Bottrop",
			"D" => "Düsseldorf",
			"DO" => "Dortmund",
			"DU" => "Duisburg",
			"E" => "Essen",
			"EN" => "Ennepe-Ruhr-Kreis",
			"GE" => "Gelsenkirchen",
			"HA" => "Hagen",
			"HER" => "Herne",
			"KR" => "Krefeld",
			"ME" => "Mettmann",
			"MG" => "Mönchengladbach",
			"MH" => "Mülheim",
			"NE" => "Neuss",
			"OB" => "Oberhausen",
			"RS" => "Remscheid",
			"SG" => "Solingen",
			"W" => "Wuppertal",
		)    
	);

?>